---
- name: Deploy Students list application
  hosts: devservers
  become: true
  gather_facts: no
  tasks:
    - name: Check is docker is installed
      shell: command docker -v
      register: docker_exists
      ignore_errors: yes

    - name: Install docker-ce
      when: docker_exists is failed
      shell: "amazon-linux-extras install docker=18.06.1 -y"

    - name: Enable Docker CE service at startup
      service:
        name: docker
        state: started
        enabled: yes
    - name: Stop running program
      shell: 'docker stop devops || true && docker rm devops || true'
    - name: Run project docker image
      shell: 'docker run -d -p 8080:8080 --name devops brillandnkuete/devops'