---
- name: Deploy Students list application
  hosts: devservers
  become: true
  gather_facts: no
  tasks:
    - name: Update all packages
      yum:
        name: '*'
        state: latest
        update_only: yes

#    - name: Ensure a list of yum packages are installed
#      yum:
#        name: "{{ packages }}"
#        state: latest
#        update_cache: yes
#      vars:
#        packages:
#          - python-pip
#          - yum-utils
#          - device-mapper-persistent-data
#          - lvm2
#          - amazon-linux-extras

    - name: Add extras repository
      shell: yum-config-manager --enable extras

    - name: Install docker-ce
      shell: "amazon-linux-extras install docker=18.06.1 -y"

    - name: Enable Docker CE service at startup
      service:
        name: docker
        state: started
        enabled: yes
    - name: Stop running program
      shell: 'docker stop devops || true && docker rm devops || true'
    - name: Run project docker image
      shell: 'docker run -d -p 80:8080 --name devops brillandnkuete/devops'